# Site settings
title: Atty Eleti
email: athyuttamre@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Atty is an undergrad studying computer science and design at Brown University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://athyuttamre.com" # the base hostname & protocol for your site
twitter_username: athyuttamre
github_username:  athyuttamre

# Build settings
markdown: kramdown
