# Site settings
title: Athyuttam Eleti
email: athyuttamre@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software engineer, product designer, and senior at Brown University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://athyuttamre.com" # the base hostname & protocol for your site
twitter_username: athyuttamre
github_username:  athyuttamre

# Build settings
markdown: kramdown
